/** Default role → permission map. Bootstrapped into DB on first start. */
const PERMISSIONS = [
  'inventory:create',
  'inventory:update',
  'inventory:publish',
  'inventory:approve',
  'inventory:delete',
  'leads:read_assigned',
  'leads:read_all',
  'leads:update',
  'bookings:manage',
  'payments:view',
  'payments:manage',
  'commissions:view',
  'dealers:approve',
  'kyc:submit',
  'kyc:read_all',
  'kyc:approve',
  'users:manage',
  'content:manage',
  'analytics:view',
  'settings:manage',
  'reviews:moderate',
  'support:manage',
  'notifications:send',
  'valuations:run',
  'testdrives:manage',
  'finance:manage',
  'insurance:manage',
];

const ROLE_PERMISSIONS = {
  customer: [],
  dealer_staff: [
    'inventory:create',
    'inventory:update',
    'leads:read_assigned',
    'leads:update',
    'testdrives:manage',
    'bookings:manage',
    'analytics:view',
    'kyc:submit',
  ],
  dealer: [
    'inventory:create',
    'inventory:update',
    'inventory:publish',
    'inventory:delete',
    'leads:read_assigned',
    'leads:update',
    'testdrives:manage',
    'bookings:manage',
    'analytics:view',
    'valuations:run',
    'kyc:submit',
  ],
  dealer_owner: [
    'inventory:create',
    'inventory:update',
    'inventory:publish',
    'inventory:delete',
    'leads:read_assigned',
    'leads:update',
    'testdrives:manage',
    'bookings:manage',
    'analytics:view',
    'valuations:run',
    'payments:view',
    'kyc:submit',
  ],
  operations: [
    'inventory:approve',
    'leads:read_all',
    'leads:update',
    'dealers:approve',
    'content:manage',
    'analytics:view',
    'reviews:moderate',
    'support:manage',
    'testdrives:manage',
    'bookings:manage',
    'notifications:send',
  ],
  finance_admin: [
    'payments:view',
    'payments:manage',
    'commissions:view',
    'finance:manage',
    'insurance:manage',
    'analytics:view',
    'bookings:manage',
  ],
  admin: [
    'inventory:create',
    'inventory:update',
    'inventory:publish',
    'inventory:approve',
    'inventory:delete',
    'leads:read_all',
    'leads:update',
    'bookings:manage',
    'payments:view',
    'payments:manage',
    'commissions:view',
    'dealers:approve',
    'users:manage',
    'content:manage',
    'analytics:view',
    'settings:manage',
    'reviews:moderate',
    'support:manage',
    'notifications:send',
    'valuations:run',
    'testdrives:manage',
    'finance:manage',
    'insurance:manage',
  ],
  super_admin: [...PERMISSIONS],
};

/** Map legacy JWT roles to canonical role keys */
const LEGACY_ROLE_MAP = {
  customer: 'customer',
  dealer: 'dealer',
  admin: 'admin',
};

function permissionsForRole(role) {
  const key = LEGACY_ROLE_MAP[role] || role;
  return ROLE_PERMISSIONS[key] || [];
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  LEGACY_ROLE_MAP,
  permissionsForRole,
};
