const mongoose = require('mongoose');

const enquirySchema = new mongoose.Schema(
  {
    type: { type: String, enum: ['finance', 'insurance', 'seller'], required: true, index: true },
    intent: { type: String, enum: ['sell', 'exchange', 'both'], default: 'sell', index: true },
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
    vehicle: { type: mongoose.Schema.Types.ObjectId, ref: 'Car', index: true },
    name: { type: String, required: true },
    phone: { type: String, required: true },
    email: { type: String, default: '' },
    city: { type: String, default: '' },
    message: { type: String, default: '' },
    // finance fields
    loanAmount: { type: Number, default: null },
    downPayment: { type: Number, default: null },
    tenureMonths: { type: Number, default: null },
    bankName: { type: String, default: '' },
    cibilBracket: { type: String, default: '' },
    employmentType: { type: String, default: '' },
    leadSource: { type: String, default: 'website' },
    // insurance fields
    insuranceType: { type: String, default: '' },
    // seller enquiry
    brand: { type: String, default: '' },
    model: { type: String, default: '' },
    variant: { type: String, default: '' },
    year: { type: Number, default: null },
    kmDriven: { type: Number, default: null },
    expectedPrice: { type: Number, default: null },
    estimatePrice: { type: Number, default: null },
    minPrice: { type: Number, default: null },
    maxPrice: { type: Number, default: null },
    valuationId: { type: mongoose.Schema.Types.ObjectId, ref: 'Valuation', default: null },
    valuationSource: { type: String, default: '' },
    valuationPending: { type: Boolean, default: false },
    photos: [{ type: String }],
    registrationNumber: { type: String, default: '' },
    rto: { type: String, default: '' },
    state: { type: String, default: '' },
    bodyType: { type: String, default: '' },
    color: { type: String, default: '' },
    fuel: { type: String, default: '' },
    transmission: { type: String, default: '' },
    ownership: { type: Number, default: null },
    inspectionType: { type: String, default: '' },
    inspectionDate: { type: String, default: '' },
    inspectionSlot: { type: String, default: '' },
    hubId: { type: String, default: '' },
    conditions: [{ type: String }],
    stageHistory: [
      {
        from: { type: String, default: '' },
        to: { type: String, default: '' },
        at: { type: Date, default: Date.now },
      },
    ],
    addOns: { type: [String], default: [] },
    policyNumber: { type: String, default: '' },
    premium: { type: Number, default: null },
    status: {
      type: String,
      enum: [
        'New',
        'Submitted',
        'Assigned',
        'In Progress',
        'Quoted',
        'Dealer Responded',
        'Under Review',
        'Pre-Approved',
        'Documents Required',
        'Disbursed',
        'Follow-up',
        'Inspection / Offer',
        'Purchased',
        'Exchanged',
        'Closed',
        'Rejected',
      ],
      default: 'Submitted',
      index: true,
    },
    partnerName: { type: String, default: '' },
    assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    documents: [{ type: String }],
    notes: { type: String, default: '' },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Enquiry', enquirySchema);
